(SELECT "CUSTOMER", "CUSTOMERNAME", "COMPANYCODE", "COMPANYCODENAME",
"CLEARINGSTATUS", "ACCOUNTINGDOCUMENT", "ACCOUNTINGDOCUMENTTYPE",
"CLEARINGACCOUNTINGDOCUMENT", "CLEARINGDATE", "ACCOUNTINGDOCUMENTITEM",
"NETDUEDATE", "NETDUEARREARSDAYS", "DOCUMENTITEMTEXT",
"FISCALYEAR", "AMOUNTINCOMPANYCODECURRENCY", "COMPANYCODECURRENCY"
FROM SAPCCW."IFIARLINEITEM"('20150503', '20150505', 'E')
WHERE "POSTINGDATE" BETWEEN '20140101' AND '20141231'
AND   ( "ITEM_TYPE_BRANCH" = 'BSEG_DEBIT_SIDE_BRANCH' )
AND   ( "FINANCIALACCOUNTTYPE" = 'D')
AND   ( "DUEITEMTYPE" = 'P' OR "DUEITEMTYPE" = 'M' OR "DUEITEMTYPE" = 'S' OR "DUEITEMTYPE" = 'N' )
AND   "MANDT" = '715'
union all
SELECT "CUSTOMER", "CUSTOMERNAME", "COMPANYCODE", "COMPANYCODENAME",
"CLEARINGSTATUS", "ACCOUNTINGDOCUMENT", "ACCOUNTINGDOCUMENTTYPE",
"CLEARINGACCOUNTINGDOCUMENT", "CLEARINGDATE", "ACCOUNTINGDOCUMENTITEM",
"NETDUEDATE", "NETDUEARREARSDAYS", "DOCUMENTITEMTEXT",
"FISCALYEAR", "AMOUNTINCOMPANYCODECURRENCY", "COMPANYCODECURRENCY"
FROM SAPCCW."IFIARLINEITEM"('20150503', '20150505', 'E')
WHERE "POSTINGDATE" BETWEEN '20140101' AND '20141231'
AND   ( "ITEM_TYPE_BRANCH" = 'BSEG_DEBIT_SIDE_BRANCH' )
AND   ( "FINANCIALACCOUNTTYPE" = 'K' )
AND   ( "DUEITEMTYPE" = 'P' OR "DUEITEMTYPE" = 'M' OR "DUEITEMTYPE" = 'S' OR "DUEITEMTYPE" = 'N' )
AND   "MANDT" = '715'
)
ORDER BY "ACCOUNTINGDOCUMENT" DESC
LIMIT 122 OFFSET 0 WITH PARAMETERS( 'LOCALE' = 'EN' )
WITH HINT(IGNORE_PLAN_CACHE);

SELECT
"DISPLAYCURRENCY"  , "NETDUEINTERVALTEXT"  ,
COUNT(*) "Z____080_SUM" , SUM( "NETDUEINTVL2AMTINDSPCRCY" ) "Z____2365_SUM" ,
SUM( "TOTALOVERDUEAMTINDSPCRCY" ) "Z____3096_SUM" ,
SUM( "NETDUELASTINTVLAMTINDSPCRCY" ) "Z____3097_SUM" ,
SUM( "NETDUEINTVL1AMTINDSPCRCY" ) "Z____2370_SUM" ,
SUM( "NETDUEINTVL3AMTINDSPCRCY" ) "Z____2371_SUM"
FROM
sapccw."IFIAPFUTACCTPAYB" ( 'EUR','M', '20150504', 30, 60, 90, 0, 'E')
WHERE
"MANDT" = '715' AND "COMPANYCODE" IN ( '0001' , '1010' )
GROUP BY
"DISPLAYCURRENCY" , "NETDUEINTERVALTEXT"
ORDER BY
"DISPLAYCURRENCY" , "NETDUEINTERVALTEXT"
WITH HINT(IGNORE_PLAN_CACHE);
