SELECT
    /* FDA READ */ /* CDS access control applied */ "FISCALYEARPERIOD" ,
    "CHARTOFACCOUNTS" ,
    "CONTROLLINGAREA" ,
    "COMPANYCODE" ,
    "COSTCENTER" ,
    "GLACCOUNT" ,
    "COMPANYCODECURRENCY" ,
    "GLOBALCURRENCY" ,
    "COSTSOURCEUNIT" ,
    "TRANSACTIONCURRENCY" ,
    COUNT(*) "COUNT" ,
    SUM( "AMOUNTINGLOBALCURRENCY" ) "AMOUNTINGLOBALCURRENCY" ,
    SUM( "AMOUNTINTRANSACTIONCURRENCY" ) "AMOUNTINTRANSACTIONCURRENCY" ,
    SUM( "VALUATIONQUANTITY" ) "VALUATIONQUANTITY" ,
    SUM( "AMOUNTINCOMPANYCODECURRENCY" ) "AMOUNTINCOMPANYCODECURRENCY"
FROM /* Entity name: I_JOURNALENTRYITEMCUBE CDS access controlled */ "IFIDOCJRNLCUBE" "I_JOURNALENTRYITEMCUBE"
WHERE "MANDT" = '900'
AND "LEDGERFISCALYEAR" = '2020'
AND "CHARTOFACCOUNTS" = 'YCOA'
AND "COMPANYCODE" = '1010'
AND "LEDGER" = '0L'
GROUP BY "FISCALYEARPERIOD" ,
    "CHARTOFACCOUNTS" ,
    "CONTROLLINGAREA" ,
    "COMPANYCODE" ,
    "COSTCENTER" ,
    "GLACCOUNT" ,
    "COMPANYCODECURRENCY" ,
    "GLOBALCURRENCY" ,
    "COSTSOURCEUNIT" ,
    "TRANSACTIONCURRENCY"
ORDER BY "I_JOURNALENTRYITEMCUBE" . "FISCALYEARPERIOD" ,
    "I_JOURNALENTRYITEMCUBE" . "COMPANYCODE" ,
    "I_JOURNALENTRYITEMCUBE" . "COSTCENTER" ,
    "I_JOURNALENTRYITEMCUBE" . "GLACCOUNT" WITH HINT(use_hex_plan, RESULT_LAG ('hana_short'));
