SELECT DISTINCT "TADIR"."OBJ_NAME"
FROM "TADIR"
LEFT OUTER JOIN "TDEVC" ON "TDEVC"."DEVCLASS" = "TADIR"."DEVCLASS"
WHERE "TADIR"."OBJECT" = 'DDLS' AND "TADIR"."PGMID" = 'R3TR' AND "TADIR"."SRCSYSTEM" = 'ER1'
    AND "TADIR"."DELFLAG" = '' AND NOT "TDEVC"."DLVUNIT" IN ( 'HOME' , 'LOCAL' , '' , 'SAPPCORE_H' , 'SAPMCORE_H' , 'SAPOCORE_H' )
    AND NOT EXISTS (
        SELECT *
        FROM "VRSD"
        WHERE "VRSD"."OBJTYPE" = 'DDLS' AND "VRSD"."OBJNAME" = "TADIR"."OBJ_NAME"
            AND "VRSD"."VERSMODE" <> 'U' )
    AND NOT EXISTS (
        SELECT *
        FROM "E071"
        INNER JOIN "E070" ON "E071"."TRKORR" = "E070"."TRKORR"
        LEFT OUTER JOIN "E070" "PARENT_E070" ON "E070"."STRKORR" = "PARENT_E070"."TRKORR"
        WHERE "E071"."PGMID" = "TADIR"."PGMID" AND "E071"."OBJECT" = "TADIR"."OBJECT"
            AND "E071"."OBJ_NAME" = "TADIR"."OBJ_NAME" AND ( "E070"."TRSTATUS" = 'R'
            OR "E070"."TRSTATUS" = 'N' ) AND ( "PARENT_E070"."TRSTATUS" = 'R'
            OR "PARENT_E070"."TRSTATUS" = 'N' OR "E070"."STRKORR" = '' ) )
            AND "TADIR"."OBJ_NAME" IN ( 'P_FTR_AMORT_GROSS_NET_FLAG' , 'P_FTR_DERIV_COMP_RULE' , 'P_FTR_DERIV_COMP_RULE_MAX' , 'P_FTR_DERIV_POS_COMP_ACCU' , 'P_FTR_INDEX_COMP_FLAG' , 'P_FTR_ORIG_POS_COMP_ACCU' , 'P_FTR_PM_STEP_INDEX_AMORT' , 'P_FTR_TRANS_BOOKING_STATE' , 'P_RDPTSET' , 'P_TRAC_CREDIT' , 'P_TRAC_DEBIT' , 'P_TRDTFLOW' , 'P_TRDTSECFLOW' , 'P_TRDTTRDTBUSTRANS' , 'P_TREASURYHISTPERIOD' , 'P_TRLTRANSPOS' , 'P_TRSTCLASFLO' , 'P_TRSYHEDGEACCTGATTRIBUTES' , 'P_TRSYPOSFLOW' , 'P_TRSYSMLTDPERENDCLSREALCLASS' , 'P_TRSYSMLTPERENDCLSPOSVALACCU' , 'P_TRSYSMLTPERENDCLSPOSVALS' , 'P_TRSYSMLTPERENDCLSPOSVALSABS' , 'P_TRSYSMLTPERENDCLSREALPOSVAL' )
/* 844433571915986 */
WITH HINT(no_dynamic_result_cache);
