-- Load TPC-DS data
IMPORT CATALOG_RETURNS, CATALOG_SALES, CUSTOMER, CUSTOMER_ADDRESS, DATE_DIM FROM '/area51/testdata/master/benchTPCDS/sf10' WITH REPLACE RENAME SCHEMA SYSTEM TO TPCDS ;
-- Foreign key is not set (but mentioned in the standard specification)
ALTER TABLE TPCDS.CATALOG_SALES ADD FOREIGN KEY (CS_SOLD_DATE_SK) REFERENCES TPCDS.DATE_DIM (D_DATE_SK);
-- Create adapted catalog_sales and catalog_returns without NULL values for cs_sold_date_sk and cs_bill_customer_sk.
-- This modification is required to guarantee the FD cs_order_number -> { cs_sold_date_sk, cs_bill_customer_sk }
-- Furthermore, the CUSTOMER table was filtered in any way and does not contain all keys anymore.
-- Thus, we also have to filter to enable the FK.
CREATE TABLE TPCDS.CATALOG_SALES_SANITIZED AS (SELECT TPCDS.CATALOG_SALES.* FROM TPCDS.CATALOG_SALES, TPCDS.CUSTOMER  WHERE CS_SOLD_DATE_SK IS NOT NULL AND CS_BILL_CUSTOMER_SK IS NOT NULL AND CS_BILL_CUSTOMER_SK = C_CUSTOMER_SK);
CREATE TABLE TPCDS.CATALOG_RETURNS_SANITIZED AS (SELECT TPCDS.CATALOG_RETURNS.* FROM  TPCDS.CATALOG_SALES_SANITIZED, TPCDS.CATALOG_RETURNS WHERE CR_ORDER_NUMBER = CS_ORDER_NUMBER AND CS_ITEM_SK = CR_ITEM_SK);
-- Add primary and foreign keys to the adapted tables
ALTER TABLE TPCDS.CATALOG_SALES_SANITIZED ADD PRIMARY KEY (CS_ITEM_SK, CS_ORDER_NUMBER);
ALTER TABLE TPCDS.CATALOG_SALES_SANITIZED ADD FOREIGN KEY (CS_SOLD_DATE_SK) REFERENCES TPCDS.DATE_DIM (D_DATE_SK);
ALTER TABLE TPCDS.CATALOG_RETURNS_SANITIZED ADD FOREIGN KEY (CR_ITEM_SK, CR_ORDER_NUMBER) REFERENCES TPCDS.CATALOG_SALES_SANITIZED (CS_ITEM_SK, CS_ORDER_NUMBER);
ALTER TABLE TPCDS.CATALOG_SALES_SANITIZED ADD FOREIGN KEY (CS_BILL_CUSTOMER_SK) REFERENCES TPCDS.CUSTOMER (C_CUSTOMER_SK);
-- Add FK to customer (also mentioned in the schema) and inform the DB that it is not nullable (there really are no NULLs).
ALTER TABLE TPCDS.CUSTOMER ADD FOREIGN KEY (C_CURRENT_ADDR_SK) REFERENCES TPCDS.CUSTOMER_ADDRESS (CA_ADDRESS_SK);
ALTER TABLE TPCDS.CUSTOMER ALTER (C_CURRENT_ADDR_SK INTEGER NOT NULL);
