SELECT "MANDT" , "LEDGER" , "COMPANYCODE" , "CUSTOMER" , "GLACCOUNT" , "SALESORGANIZATION" , "PRODUCTGROUP" , "PROFITCENTER" , "SOLDPRODUCTGROUP" ,
       "GLACCOUNTHIERARCHY" , "CUSTOMERGROUP" , "MATERIALGROUP" , "SALESDISTRICT" , "POSTINGDATE" , "ORDERID" , "CONTROLLINGAREA" , "COSTCENTER" ,
       "SALESDOCUMENT" , "CUSTOMERSUPPLIERCOUNTRY" , "CUSTOMERSUPPLIERINDUSTRY" , "GLOBALCURRENCY" , "ACCOUNTINGDOCUMENTTYPE" , "PLANNINGCATEGORY" ,
       "DISTRIBUTIONCHANNEL" , "DIVISION" , "GLACCOUNTNAME" , "ACTLSLSDEDUCTIONAMTINGLOBCRCY" , "PLNSLSDEDUCTIONAMTINGLOBCRCY" ,
       "LASTYRACTLSLSDDCTDAMTINGCRCY" , "ACTLPLNDIFFAMTINGLOBALCRCY" , "ACTLPREVDIFFAMTINGCRCY" , "PLANT" , "VALUATIONAREA" , "ORGANIZATIONDIVISION" ,
       "BUSINESSAREA" , "FINANCIALACCOUNTTYPE" , "SEGMENT" , "SUPPLIER" , "SERVICEDOCUMENTTYPE" , "SERVICEDOCUMENT" , "ASSETCLASS"
FROM /* Entity name: I_SLSACCTGDEDUCTIONSOVW WITH PRIVILEGED ACCESS */ "ISLSACCSD1" ( "P_COMPANYCODE" => '1010' , "P_PLANNINGCATEGORY" => 'ACT01' , "P_INTERVAL1YEAR" => '2021' , "P_INTERVAL2YEAR" => '2020' , "P_INTERVAL1FROMFISCALPERIOD" => '001' , "P_INTERVAL2FROMFISCALPERIOD" => '001' , "P_INTERVAL1TOFISCALPERIOD" => '002' , "P_INTERVAL2TOFISCALPERIOD" => '002' ) "I_SLSACCTGDEDUCTIONSOVW"
WHERE "MANDT" = '715' AND "COMPANYCODE" = '1010' AND "CONTROLLINGAREA" = 'A000' AND "COSTCENTER" = '' AND "CUSTOMER" = '0066660003' AND "CUSTOMERGROUP" = '01' AND "GLACCOUNT" = '0044002000'
  AND "GLACCOUNTHIERARCHY" = 'YPS2' AND "LEDGER" = '2L' AND "MATERIALGROUP" = 'L001' AND "ORDERID" = '' AND "POSTINGDATE" = '20200121' AND "PRODUCTGROUP" = '' AND "PROFITCENTER" = 'YB700'
  AND "SALESDISTRICT" = '' AND "SALESDOCUMENT" = '30000417' AND "SALESORGANIZATION" = '1010' AND "SOLDPRODUCTGROUP" = 'L001'
LIMIT 1
WITH HINT(/*TEST2:I_SLSACCTGDEDUCTIONSOVW:1010,ACT01,2021,2020,001,001,002,002,715,1010,A000,,0066660003,01,0044002000,YPS2,2L,L001,,20200121,,YB700,,30000417,1010,L001 */ no_dynamic_result_cache);
