SELECT *
          FROM SAPQM7."V_KONV_CDS"
          WHERE "MANDT" = '910' AND "KNUMV" = '1000014550'
          ORDER BY "V_KONV_CDS"."MANDT", "V_KONV_CDS"."KNUMV", "V_KONV_CDS"."KPOSN", "V_KONV_CDS"."STUNR", "V_KONV_CDS"."ZAEHK";


SELECT *
          FROM SAPQM7."V_KONV_CDS"
          WHERE "MANDT" = '910' AND "KNUMV" = '1000014550'
          ORDER BY "V_KONV_CDS"."MANDT", "V_KONV_CDS"."KNUMV", "V_KONV_CDS"."KPOSN", "V_KONV_CDS"."STUNR", "V_KONV_CDS"."ZAEHK"
          WITH HINT (MAX_CONCURRENCY(1));
